name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild Docker image on server & Run
        uses: appleboy/ssh-action@master
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_API_CX: ${{ secrets.GOOGLE_API_CX }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 200m
          envs: GOOGLE_API_KEY,GOOGLE_API_CX
          script: |
            cd projects/seo-serps
            GIT_SSH_COMMAND='ssh -i ~/.ssh/git -o IdentitiesOnly=yes' git pull
            docker build -t seo-serps \
            --build-arg GOOGLE_API_KEY_ARG=${GOOGLE_API_KEY} \
            --build-arg GOOGLE_API_CX_ARG=${GOOGLE_API_CX} \
            .
            docker stop seo-serps-container
            docker rm seo-serps-container
            docker run -d -t --restart=always --name seo-serps-container -p 5648:8080 --net nginx-proxy -e VIRTUAL_HOST=seo-serps.glecun-raspberry.duckdns.org seo-serps